#Proyecto easy money

##Primeros pasos 
* Conectar el note book con google drive.
* Importar los modulos que nos ser√°n necesarios.
* Importas los csv y conbertirlos en df 
* Analizar los datos de lso diferentes df.
* Juntar los diferentes df.
* Tratar las diferentes variables

In [ ]:
#conectamos google colab con el drive 

from google.colab import drive
drive.mount('/content/drive')




Importamos librerias

In [ ]:
# importamos las diferentes librerias pandas numpy ...

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

### Importamos los csv y creamos los diferentes data frames para su posterior analisis

In [ ]:
commercial_activity_df= pd.read_csv('/content/drive/MyDrive/Proyecto Final/data/commercial_activity_df.csv', index_col=[0])

/usr/local/lib/python3.7/dist-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [ ]:
products_df= pd.read_csv('/content/drive/MyDrive/Proyecto Final/data/products_df.csv', index_col=[0])

/usr/local/lib/python3.7/dist-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [ ]:
sociodemographic_df= pd.read_csv('/content/drive/MyDrive/Proyecto Final/data/sociodemographic_df.csv', index_col=[0])

/usr/local/lib/python3.7/dist-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

##Analizamos cada DataSets

In [ ]:
#Primer data frame commercial_activity

commercial_activity_df.head(2)

    pk_cid pk_partition  ... active_customer             segment
0  1375586   2018-01-28  ...             1.0   02 - PARTICULARES
1  1050611   2018-01-28  ...             0.0  03 - UNIVERSITARIO

[2 rows x 6 columns]

In [ ]:
commercial_activity_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962924 entries, 0 to 13647308
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   pk_cid           int64
 1   pk_partition     object
 2   entry_date       object
 3   entry_channel    object
 4   active_customer  float64
 5   segment          object
dtypes: float64(1), int64(1), object(4)
memory usage: 318.5+ MB

In [ ]:
#segundo data frame sociodemographic_df
sociodemographic_df.head(2)

    pk_cid pk_partition country_id  region_code gender  age deceased    salary
0  1375586   2018-01-28         ES         29.0      H   35        N  87218.10
1  1050611   2018-01-28         ES         13.0      V   23        N  35548.74

In [ ]:
sociodemographic_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962924 entries, 0 to 13647308
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   pk_cid        int64
 1   pk_partition  object
 2   country_id    object
 3   region_code   float64
 4   gender        object
 5   age           int64
 6   deceased      object
 7   salary        float64
dtypes: float64(2), int64(2), object(4)
memory usage: 409.4+ MB

In [ ]:
#tercer data frame products_df
products_df.head(2)

    pk_cid pk_partition  ...  em_account_p  em_acount
0  1375586   2018-01-28  ...             0          1
1  1050611   2018-01-28  ...             0          1

[2 rows x 17 columns]

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962924 entries, 0 to 13647308
Data columns (total 17 columns):
 #   Column              Dtype
---  ------              -----
 0   pk_cid              int64
 1   pk_partition        object
 2   short_term_deposit  int64
 3   loans               int64
 4   mortgage            int64
 5   funds               int64
 6   securities          int64
 7   long_term_deposit   int64
 8   em_account_pp       int64
 9   credit_card         int64
 10  payroll             float64
 11  pension_plan        float64
 12  payroll_account     int64
 13  emc_account         int64
 14  debit_card          int64
 15  em_account_p        int64
 16  em_acount           int64
dtypes: float64(2), int64(14), object(1)
memory usage: 818.9+ MB

### una vez visualizados los diferentes df procedemos a unirlos en unos solo
###para esto usaremos un merge 

para hacer el merge entre los diferentes data frames vamos a aprovechar la columna que comparten todos que es el "pk_cid", que no es m√°s que el identificador del cliente.

In [ ]:
#primero creamos el df0 y hacemos un merge con los df commercial_activity y sociodemographic,
# una vez juntados estos dos, podemos proceder a unir el siguiente df.


df0 = pd.merge(commercial_activity_df,sociodemographic_df,how="right", on=["pk_cid","pk_partition"])

In [ ]:
#Comprobamos que los data frame se unieron correctamente.

df0.head()

    pk_cid pk_partition  entry_date  ... age  deceased     salary
0  1375586   2018-01-28  2018-01-12  ...  35         N   87218.10
1  1050611   2018-01-28  2015-08-10  ...  23         N   35548.74
2  1050612   2018-01-28  2015-08-10  ...  23         N  122179.11
3  1050613   2018-01-28  2015-08-10  ...  22         N  119775.54
4  1050614   2018-01-28  2015-08-10  ...  23         N        NaN

[5 rows x 12 columns]

In [ ]:
#todo est√° correcto asi que procederemos a unir el siguiente data frame

In [ ]:
df0.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962924 entries, 0 to 5962923
Columns: 12 entries, pk_cid to salary
dtypes: float64(3), int64(2), object(7)
memory usage: 591.4+ MB

In [ ]:
#Ahora indicamos que queremos unir el df0 con el products_df de esta manera estarian los 3 data frames unidos en df0


df = pd.merge(df0,products_df,how="right", on=["pk_cid","pk_partition"])

##Primer analisis de los datos

In [ ]:
df.head().T

                                    0  ...                   4
pk_cid                        1375586  ...             1050614
pk_partition               2018-01-28  ...          2018-01-28
entry_date                 2018-01-12  ...          2015-08-10
entry_channel                     KHL  ...                 KHE
active_customer                     1  ...                   1
segment             02 - PARTICULARES  ...  03 - UNIVERSITARIO
country_id                         ES  ...                  ES
region_code                        29  ...                  50
gender                              H  ...                   V
age                                35  ...                  23
deceased                            N  ...                   N
salary                        87218.1  ...                 NaN
short_term_deposit                  0  ...                   0
loans                               0  ...                   0
mortgage                            0  ...                   0
funds                               0  ...                   0
securities                          0  ...                   0
long_term_deposit                   0  ...                   0
em_account_pp                       0  ...                   0
credit_card                         0  ...                   0
payroll                             0  ...                   0
pension_plan                        0  ...                   0
payroll_account                     0  ...                   0
emc_account                         0  ...                   0
debit_card                          0  ...                   0
em_account_p                        0  ...                   0
em_acount                           1  ...                   1

[27 rows x 5 columns]

In [ ]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962924 entries, 0 to 5962923
Columns: 27 entries, pk_cid to em_acount
dtypes: float64(5), int64(15), object(7)
memory usage: 1.2+ GB

In [ ]:
df.shape

(5962924, 27)

**Podemos observar que nuestro data frame tiene 5.962.924 filas y 27 columnas**
---
###Ahora revisaremos si existen datos duplicados

In [ ]:
#con este c√≥digo nos damos cuenta que el data frame est√° limpio de duplicados
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, region_code, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

##Una vez revisados los duplicados miramos los nulos

In [ ]:
# Aqu√≠ vemos el nombre de las columnas que contienen nulos 
null_data=df.columns[df.isnull().any()]
null_data

Index(['entry_channel', 'segment', 'region_code', 'gender', 'salary',
       'payroll', 'pension_plan'],
      dtype='object')

In [ ]:
# Ahora hacemos una suma donde vemos el total de nulos por cada columna
df.isnull().sum()

pk_cid                      0
pk_partition                0
entry_date                  0
entry_channel          133033
active_customer             0
segment                133944
country_id                  0
region_code              2264
gender                     25
age                         0
deceased                    0
salary                1512103
short_term_deposit          0
loans                       0
mortgage                    0
funds                       0
securities                  0
long_term_deposit           0
em_account_pp               0
credit_card                 0
payroll                    61
pension_plan               61
payroll_account             0
emc_account                 0
debit_card                  0
em_account_p                0
em_acount                   0
dtype: int64

In [ ]:
#Aqu√≠ vemos cuales de las columnas n√∫mericas tienen valores nulos 
df.select_dtypes(include=['number']).isnull().sum()

pk_cid                      0
active_customer             0
region_code              2264
age                         0
salary                1512103
short_term_deposit          0
loans                       0
mortgage                    0
funds                       0
securities                  0
long_term_deposit           0
em_account_pp               0
credit_card                 0
payroll                    61
pension_plan               61
payroll_account             0
emc_account                 0
debit_card                  0
em_account_p                0
em_acount                   0
dtype: int64

In [ ]:
#Aqu√≠ vemos cuales de las columnas NO n√∫mericas tienen nulos 
df.select_dtypes(include=['object']).isnull().sum()

pk_partition          0
entry_date            0
entry_channel    133033
segment          133944
country_id            0
gender               25
deceased              0
dtype: int64

###Ahora empezaremos a hacer el tratamiento de los nulos, vamos a empezar por explorar la variable 'segment'.

In [ ]:
#aqu√≠ podemos ver que hay 133.944 nulos en las variable segment

df[df['segment'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
18665    1060507   2018-01-28  2015-10-17  ...          0             0         0
30736    1035728   2018-01-28  2015-07-30  ...          0             0         1
33894    1040205   2018-01-28  2015-08-02  ...          0             0         0
52580    1125388   2018-01-28  2016-03-22  ...          0             0         1
57463    1115187   2018-01-28  2015-12-31  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5947993  1185013   2019-05-28  2019-05-14  ...          0             0         1
5956953  1168909   2019-05-28  2016-08-23  ...          0             0         1
5958078  1173729   2019-05-28  2016-09-09  ...          0             0         1
5960641  1164094   2019-05-28  2019-05-13  ...          0             0         1
5962923  1550586   2019-05-28  2019-05-13  ...          0             0         1

[133944 rows x 27 columns]

###Vamos a comprobar que valores coje la variable

In [ ]:
#podemos observar que solo tiene 4 valores posibles, los valores que a continuaci√≥n se nos muestran
#como indefinidos en el data frame son valores nulos, as√≠ que los transformaremos de nulos en data frame
#a indefinido

df['segment'].unique()

array(['02 - PARTICULARES', '03 - UNIVERSITARIO', '01 - TOP',
       '04 - INDEFINIDO'], dtype=object)

##Aqu√≠ aplicamos que todos los valores que tengan nulos, pasen a tener el valor 
##indefinido.

In [ ]:
df['segment'].fillna('04 - INDEFINIDO', inplace= True)

In [ ]:
#observamos que la variable segment ya no tiene nulos
df[df['segment'].isnull()]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, region_code, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
df.head()

    pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
0  1375586   2018-01-28  2018-01-12  ...          0             0         1
1  1050611   2018-01-28  2015-08-10  ...          0             0         1
2  1050612   2018-01-28  2015-08-10  ...          0             0         1
3  1050613   2018-01-28  2015-08-10  ...          0             0         0
4  1050614   2018-01-28  2015-08-10  ...          0             0         1

[5 rows x 27 columns]

In [ ]:
#Seguimos comprobando que variables tienen nulos 
null_data=df.columns[df.isnull().any()]
null_data

Index(['entry_channel', 'region_code', 'gender', 'salary', 'payroll',
       'pension_plan'],
      dtype='object')

###Ahora trabajaremos la variable "entry_channel"

In [ ]:
df[df['entry_channel'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
30736    1035728   2018-01-28  2015-07-30  ...          0             0         1
33894    1040205   2018-01-28  2015-08-02  ...          0             0         0
57463    1115187   2018-01-28  2015-12-31  ...          0             0         1
74663    1083617   2018-01-28  2015-10-18  ...          0             0         0
88417    1286622   2018-01-28  2017-07-31  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5947928  1185110   2019-05-28  2016-09-27  ...          0             0         0
5947993  1185013   2019-05-28  2019-05-14  ...          0             0         1
5956953  1168909   2019-05-28  2016-08-23  ...          0             0         1
5958078  1173729   2019-05-28  2016-09-09  ...          0             0         1
5962923  1550586   2019-05-28  2019-05-13  ...          0             0         1

[133033 rows x 27 columns]

####Podemos observar que hay 133.033 entradas nulas y a continuaci√≥n vemos que hay un gran numero de posibles valores para la variable

In [ ]:
df['entry_channel'].unique()

array(['KHL', 'KHE', 'KHD', 'KFA', 'KFC', 'KAT', 'KAZ', 'RED', 'KHC',
       'KHK', 'KGN', 'KHM', 'KHO', 'KDH', 'KEH', 'KAD', 'KBG', nan, 'KGC',
       'KHF', 'KFK', 'KHN', 'KAB', 'KAG', 'KAA', 'KGX', 'KAR', 'KAK',
       'KBZ', '007', 'KBO', 'KCB', '013', 'KAY', 'KBE', 'KAS', 'KCL',
       '004', 'KAF', 'KCC', 'KEY', 'KDT', 'KAQ', 'KAH', 'KAM', 'KAJ',
       'KFD', 'KCH', 'KFS', 'KAW', 'KAE', 'KBH', 'KDR', 'KHQ', 'KBW',
       'KBY', 'KCI', 'KEJ', 'KFF', 'KBU', 'KAI', 'KCK', 'KDA', 'KES',
       'KHP', 'KFL', 'KDS', 'KFP', 'KHS'], dtype=object)

In [ ]:
#vemos que hay 68 posibles valores para la variable, ademas de cuales son los valores que m√°s se repiten y los que menos 
df['entry_channel'].value_counts()

KHE    3113947
KFC     890620
KHQ     590280
KAT     416084
KHK     230197
        ...
KEJ          8
KHS          5
KFP          2
KDA          2
KDS          1
Name: entry_channel, Length: 68, dtype: int64

Con estas observaciones vamos a cojer todas las etiquetas con nulos y las pasaremos a un valor que sea sin codigo.

---

In [ ]:
#cambiamos el valor en el df de nulos  a sin codigo.
df['entry_channel'].fillna('Sin Codigo', inplace= True)

In [ ]:
#comprobamos que la variable ya no tiene nulos
df[df['entry_channel'].isnull()]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, region_code, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
#comprobamos nuevamente que variables tienen nulos.
null_data=df.columns[df.isnull().any()]
null_data

Index(['region_code', 'gender', 'salary', 'payroll', 'pension_plan'], dtype='object')

In [ ]:
df.isnull().sum()

Ahora trataremos 'payroll' y 'pension_plan', ya que estas dos variables est√°n directamente relacionadas porqu√© tiene el mismo n√∫mero de nulos

---

#bajo que criterio se les inputa el valor 0.0 ???

---

In [ ]:
#vemos la cantidad de nulos que tiene 
df[df['payroll'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
20679    1023793   2018-01-28  2015-07-17  ...          0             0         0
45769    1097831   2018-01-28  2015-11-08  ...          0             0         0
51586    1132935   2018-01-28  2016-05-03  ...          0             0         0
56072    1118340   2018-01-28  2016-01-17  ...          0             0         0
102989   1266281   2018-01-28  2017-06-30  ...          0             0         0
...          ...          ...         ...  ...        ...           ...       ...
1174495  1164621   2018-05-28  2016-08-13  ...          0             0         0
1193187  1263889   2018-05-28  2017-06-17  ...          0             0         0
1194282  1261206   2018-05-28  2017-06-02  ...          0             0         0
1199121  1251445   2018-05-28  2017-04-01  ...          0             0         0
1213934  1221067   2018-05-28  2016-11-18  ...          0             0         0

[61 rows x 27 columns]

In [ ]:
df[df['pension_plan'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
20679    1023793   2018-01-28  2015-07-17  ...          0             0         0
45769    1097831   2018-01-28  2015-11-08  ...          0             0         0
51586    1132935   2018-01-28  2016-05-03  ...          0             0         0
56072    1118340   2018-01-28  2016-01-17  ...          0             0         0
102989   1266281   2018-01-28  2017-06-30  ...          0             0         0
...          ...          ...         ...  ...        ...           ...       ...
1174495  1164621   2018-05-28  2016-08-13  ...          0             0         0
1193187  1263889   2018-05-28  2017-06-17  ...          0             0         0
1194282  1261206   2018-05-28  2017-06-02  ...          0             0         0
1199121  1251445   2018-05-28  2017-04-01  ...          0             0         0
1213934  1221067   2018-05-28  2016-11-18  ...          0             0         0

[61 rows x 27 columns]

In [ ]:
df[(df['pension_plan']!= 'NaN') & (df['payroll']!= 'NaN')]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
0        1375586   2018-01-28  2018-01-12  ...          0             0         1
1        1050611   2018-01-28  2015-08-10  ...          0             0         1
2        1050612   2018-01-28  2015-08-10  ...          0             0         1
3        1050613   2018-01-28  2015-08-10  ...          0             0         0
4        1050614   2018-01-28  2015-08-10  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5962919  1166765   2019-05-28  2016-08-14  ...          0             0         1
5962920  1166764   2019-05-28  2016-08-14  ...          0             0         1
5962921  1166763   2019-05-28  2016-08-14  ...          0             0         1
5962922  1166789   2019-05-28  2016-08-14  ...          0             0         1
5962923  1550586   2019-05-28  2019-05-13  ...          0             0         1

[5962924 rows x 27 columns]

In [ ]:
df[(df['pension_plan']!= 0.0) & (df['payroll']!= 0.0)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
72       1050659   2018-01-28  2015-08-10  ...          1             0         0
121      1050565   2018-01-28  2015-08-10  ...          1             0         0
141      1050537   2018-01-28  2015-08-10  ...          0             0         0
187      1050869   2018-01-28  2015-08-10  ...          1             0         0
223      1050920   2018-01-28  2015-08-10  ...          0             0         0
...          ...          ...         ...  ...        ...           ...       ...
5962686  1167089   2019-05-28  2016-08-16  ...          1             0         0
5962687  1167088   2019-05-28  2016-08-16  ...          1             0         0
5962719  1166671   2019-05-28  2016-08-14  ...          1             0         0
5962753  1166666   2019-05-28  2016-08-14  ...          1             0         0
5962872  1166753   2019-05-28  2016-08-14  ...          1             0         0

[205848 rows x 27 columns]

In [ ]:
df['payroll'].fillna(0.0, inplace= True)

In [ ]:
df['pension_plan'].fillna(0.0, inplace= True)

#bajo que criterio se les inputa el valor 0.0 ???

---

In [ ]:
#seguimos revisando que valores tienen nulos.
df.isnull().sum()

pk_cid                      0
pk_partition                0
entry_date                  0
entry_channel               0
active_customer             0
segment                     0
country_id                  0
region_code              2264
gender                     25
age                         0
deceased                    0
salary                1512103
short_term_deposit          0
loans                       0
mortgage                    0
funds                       0
securities                  0
long_term_deposit           0
em_account_pp               0
credit_card                 0
payroll                     0
pension_plan                0
payroll_account             0
emc_account                 0
debit_card                  0
em_account_p                0
em_acount                   0
dtype: int64

###Vamos a trabajar la variable gender, que tiene pocos nulos.

---

In [ ]:
#vemos cuantos nulos tiene y si est√° relacionado con otra variable.
df[df['gender'].isnull()]

         pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
482482   476023   2018-03-28  2018-03-12  ...          0             0         1
727801   476023   2018-04-28  2018-03-12  ...          0             0         1
1224152  476023   2018-05-28  2018-03-12  ...          1             0         1
1476252  476023   2018-06-28  2018-03-12  ...          1             0         1
1477367  476023   2018-07-28  2018-03-12  ...          1             0         1
1842989  476023   2018-08-28  2018-03-12  ...          1             0         1
2168807  216507   2018-08-28  2018-08-17  ...          0             0         0
2169657  476023   2018-09-28  2018-03-12  ...          1             0         1
2172127  216507   2018-09-28  2018-08-17  ...          0             0         0
2943933  216507   2018-10-28  2018-08-17  ...          0             0         0
2946003  476023   2018-10-28  2018-03-12  ...          1             0         1
2953625  476023   2018-11-28  2018-03-12  ...          1             0         1
3033652  216507   2018-11-28  2018-08-17  ...          0             0         0
3627544  216507   2018-12-28  2018-08-17  ...          0             0         0
3629885  476023   2018-12-28  2018-03-12  ...          1             0         1
3839882  216507   2019-01-28  2018-08-17  ...          0             0         0
4102914  476023   2019-01-28  2018-03-12  ...          1             0         1
4478901  476023   2019-02-28  2018-03-12  ...          1             0         1
4481238  216507   2019-02-28  2018-08-17  ...          0             0         0
4875861  216507   2019-03-28  2018-08-17  ...          0             0         0
4887017  476023   2019-03-28  2018-03-12  ...          1             0         1
5133231  216507   2019-04-28  2018-08-17  ...          0             0         0
5133985  476023   2019-04-28  2018-03-12  ...          1             0         1
5523191  216507   2019-05-28  2018-08-17  ...          0             0         0
5524103  476023   2019-05-28  2018-03-12  ...          1             0         1

[25 rows x 27 columns]

###Considerando que son pocos valores nulos, y que la etiqueta solo tiene dos posibles valores, vamos a asignarle los nulos al valor V

In [ ]:
df['gender'].value_counts()

H    3087502
V    2875397
Name: gender, dtype: int64

In [ ]:
df['gender'].fillna('V', inplace= True)

In [ ]:
df['gender'].value_counts()

H    3087502
V    2875422
Name: gender, dtype: int64

In [ ]:
#Aqu√≠ comprobamos que hemos hecho la asignaci√≥n correctamente 
df[df['gender'].isnull()]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, region_code, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

Continuamos nalizando variables y vamos esta vez con salary

---

In [ ]:
df[df['salary'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
4        1050614   2018-01-28  2015-08-10  ...          0             0         1
8        1050619   2018-01-28  2015-08-10  ...          0             0         1
11       1050622   2018-01-28  2015-08-10  ...          0             0         1
14       1050625   2018-01-28  2015-08-10  ...          0             0         1
15       1050626   2018-01-28  2015-08-10  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5962906  1166778   2019-05-28  2016-08-14  ...          0             0         1
5962908  1166776   2019-05-28  2016-08-16  ...          0             0         1
5962913  1166771   2019-05-28  2016-08-16  ...          0             0         1
5962921  1166763   2019-05-28  2016-08-14  ...          0             0         1
5962923  1550586   2019-05-28  2019-05-13  ...          0             0         1

[1512103 rows x 27 columns]

In [ ]:
df['salary'].mean()

115816.72370448668

In [ ]:
df['salary'].median()

88654.65

Agrupamos por Segmento(pendiente por mirar no lo han dado en clases)

In [ ]:
df['salary'].groupby(df['segment']).mean()

segment
01 - TOP              148448.090709
02 - PARTICULARES     115887.830537
03 - UNIVERSITARIO    114978.212778
04 - INDEFINIDO       113070.572915
Name: salary, dtype: float64

In [ ]:
df['salary'].groupby(df['segment']).median()

segment
01 - TOP              121240.92
02 - PARTICULARES      89034.06
03 - UNIVERSITARIO     87855.18
04 - INDEFINIDO        87605.88
Name: salary, dtype: float64

Coloco la media del salario por segmento

In [ ]:
df['salary'] = df['salary'].fillna(df.groupby('segment')['salary'].transform('mean'))

In [ ]:
df.groupby('segment')['salary'].transform('mean')

0          115887.830537
1          114978.212776
2          114978.212776
3          114978.212776
4          114978.212776
               ...
5962919    114978.212776
5962920    114978.212776
5962921    115887.830537
5962922    114978.212776
5962923    113070.572916
Name: salary, Length: 5962924, dtype: float64

In [ ]:
df[df['salary'].isnull()]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
df[df['salary']==114978.212778]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
df[df['pk_cid']==1050614]
##esta bien la union y la segmentaci√≥n de salarios, si nos fijamos el pk_partition es mensual no es el mismo mes.

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
4        1050614   2018-01-28  2015-08-10  ...          0             0         1
472595   1050614   2018-02-28  2015-08-10  ...          0             0         1
693179   1050614   2018-03-28  2015-08-10  ...          0             0         1
969534   1050614   2018-04-28  2015-08-10  ...          0             0         1
981489   1050614   2018-05-28  2015-08-10  ...          0             0         1
1257176  1050614   2018-06-28  2015-08-10  ...          0             0         1
1581539  1050614   2018-07-28  2015-08-10  ...          0             0         1
2050109  1050614   2018-08-28  2015-08-10  ...          0             0         1
2331061  1050614   2018-09-28  2015-08-10  ...          0             0         1
2673595  1050614   2018-10-28  2015-08-10  ...          0             0         1
3335097  1050614   2018-11-28  2015-08-10  ...          0             0         1
3416911  1050614   2018-12-28  2015-08-10  ...          0             0         1
4162355  1050614   2019-01-28  2015-08-10  ...          0             0         1
4547654  1050614   2019-02-28  2015-08-10  ...          0             0         1
5079144  1050614   2019-03-28  2015-08-10  ...          0             0         1
5269796  1050614   2019-04-28  2015-08-10  ...          0             0         1
5774189  1050614   2019-05-28  2015-08-10  ...          0             0         1

[17 rows x 26 columns]

Continuamos ahora con el campo 'region_code'

In [ ]:
df[df['region_code'].isnull()]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
2022     1050073   2018-01-28  2015-08-10  ...          1             0         1
4121     1052929   2018-01-28  2015-08-20  ...          0             0         1
4320     1054714   2018-01-28  2015-08-29  ...          0             0         0
5874     1044441   2018-01-28  2015-08-06  ...          0             0         1
15144    1058997   2018-01-28  2015-09-12  ...          1             0         0
...          ...          ...         ...  ...        ...           ...       ...
5958237  1173247   2019-05-28  2016-09-06  ...          0             0         0
5958805  1171742   2019-05-28  2016-09-02  ...          0             0         1
5961554  1167439   2019-05-28  2016-08-19  ...          0             0         1
5961786  1168237   2019-05-28  2016-08-21  ...          0             0         1
5962655  1167044   2019-05-28  2016-08-16  ...          0             0         0

[2264 rows x 27 columns]

In [ ]:
df['region_code'].dtype

dtype('float64')

In [ ]:
df['country_id'].dtype

dtype('O')

In [ ]:
df[['country_id','region_code']].isnull().sum()

country_id        0
region_code    2264
dtype: int64

In [ ]:
df[df['country_id']=='ES'].isnull().sum()

pk_cid                 0
pk_partition           0
entry_date             0
entry_channel          0
active_customer        0
segment                0
country_id             0
region_code           12
gender                 0
age                    0
deceased               0
salary                 0
short_term_deposit     0
loans                  0
mortgage               0
funds                  0
securities             0
long_term_deposit      0
em_account_pp          0
credit_card            0
payroll                0
pension_plan           0
payroll_account        0
emc_account            0
debit_card             0
em_account_p           0
em_acount              0
dtype: int64

In [ ]:
df[df['country_id']!='ES'].isnull().sum()

pk_cid                   0
pk_partition             0
entry_date               0
entry_channel            0
active_customer          0
segment                  0
country_id               0
region_code           2252
gender                   0
age                      0
deceased                 0
salary                   0
short_term_deposit       0
loans                    0
mortgage                 0
funds                    0
securities               0
long_term_deposit        0
em_account_pp            0
credit_card              0
payroll                  0
pension_plan             0
payroll_account          0
emc_account              0
debit_card               0
em_account_p             0
em_acount                0
dtype: int64

In [ ]:
df['region_code']

0          29.0
1          13.0
2          13.0
3          50.0
4          50.0
           ...
5962919    50.0
5962920    26.0
5962921    50.0
5962922    50.0
5962923    28.0
Name: region_code, Length: 5962924, dtype: float64

Antes de eliminar el campo mirar como colocar los 12 nulos de espa√±a con la moda de espa√±a

Veo que el campo region_code se puede eliminar

In [ ]:
#df['region_code'].fillna(100.0, inplace= True)

In [ ]:
##df[sociodemographic_df['region_code']==100.0]

In [ ]:
df.isnull().sum()

pk_cid                   0
pk_partition             0
entry_date               0
entry_channel            0
active_customer          0
segment                  0
country_id               0
region_code           2264
gender                   0
age                      0
deceased                 0
salary                   0
short_term_deposit       0
loans                    0
mortgage                 0
funds                    0
securities               0
long_term_deposit        0
em_account_pp            0
credit_card              0
payroll                  0
pension_plan             0
payroll_account          0
emc_account              0
debit_card               0
em_account_p             0
em_acount                0
dtype: int64

In [ ]:
df.drop(["region_code"], axis=1, inplace=True)

In [ ]:
df.isnull().sum()

pk_cid                0
pk_partition          0
entry_date            0
entry_channel         0
active_customer       0
segment               0
country_id            0
gender                0
age                   0
deceased              0
salary                0
short_term_deposit    0
loans                 0
mortgage              0
funds                 0
securities            0
long_term_deposit     0
em_account_pp         0
credit_card           0
payroll               0
pension_plan          0
payroll_account       0
emc_account           0
debit_card            0
em_account_p          0
em_acount             0
dtype: int64

Reviso que no queden nulos

In [ ]:
df.select_dtypes(include=['object']).isnull().sum()

pk_partition     0
entry_date       0
entry_channel    0
segment          0
country_id       0
gender           0
deceased         0
dtype: int64

In [ ]:
df.select_dtypes(include=['number']).isnull().sum()

pk_cid                0
active_customer       0
age                   0
salary                0
short_term_deposit    0
loans                 0
mortgage              0
funds                 0
securities            0
long_term_deposit     0
em_account_pp         0
credit_card           0
payroll               0
pension_plan          0
payroll_account       0
emc_account           0
debit_card            0
em_account_p          0
em_acount             0
dtype: int64

In [ ]:
df.head()

    pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
0  1375586   2018-01-28  2018-01-12  ...          0             0         1
1  1050611   2018-01-28  2015-08-10  ...          0             0         1
2  1050612   2018-01-28  2015-08-10  ...          0             0         1
3  1050613   2018-01-28  2015-08-10  ...          0             0         0
4  1050614   2018-01-28  2015-08-10  ...          0             0         1

[5 rows x 26 columns]

In [ ]:
df.reset_index(drop = True, inplace= True)

In [ ]:
df.head().T

                                    0  ...                   4
pk_cid                        1375586  ...             1050614
pk_partition               2018-01-28  ...          2018-01-28
entry_date                 2018-01-12  ...          2015-08-10
entry_channel                     KHL  ...                 KHE
active_customer                     1  ...                   1
segment             02 - PARTICULARES  ...  03 - UNIVERSITARIO
country_id                         ES  ...                  ES
gender                              H  ...                   V
age                                35  ...                  23
deceased                            N  ...                   N
salary                        87218.1  ...              114978
short_term_deposit                  0  ...                   0
loans                               0  ...                   0
mortgage                            0  ...                   0
funds                               0  ...                   0
securities                          0  ...                   0
long_term_deposit                   0  ...                   0
em_account_pp                       0  ...                   0
credit_card                         0  ...                   0
payroll                             0  ...                   0
pension_plan                        0  ...                   0
payroll_account                     0  ...                   0
emc_account                         0  ...                   0
debit_card                          0  ...                   0
em_account_p                        0  ...                   0
em_acount                           1  ...                   1

[26 rows x 5 columns]

Analizo ventas por campo

In [ ]:
df['short_term_deposit'].value_counts()

0    5947530
1      15394
Name: short_term_deposit, dtype: int64

In [ ]:
df[df['short_term_deposit']==1].T

                               3        ...            5834085
pk_cid                         1050613  ...            1013549
pk_partition                2018-01-28  ...         2019-05-28
entry_date                  2015-08-10  ...         2015-04-25
entry_channel                      KHD  ...                KAT
active_customer                      0  ...                  1
segment             03 - UNIVERSITARIO  ...  02 - PARTICULARES
country_id                          ES  ...                 ES
gender                               H  ...                  V
age                                 22  ...                 62
deceased                             N  ...                  N
salary                          119776  ...             126433
short_term_deposit                   1  ...                  1
loans                                0  ...                  0
mortgage                             0  ...                  0
funds                                0  ...                  0
securities                           0  ...                  0
long_term_deposit                    0  ...                  1
em_account_pp                        0  ...                  0
credit_card                          0  ...                  0
payroll                              0  ...                  0
pension_plan                         0  ...                  0
payroll_account                      0  ...                  0
emc_account                          0  ...                  1
debit_card                           0  ...                  1
em_account_p                         0  ...                  0
em_acount                            0  ...                  1

[26 rows x 15394 columns]

In [ ]:
df[(df['pk_partition']>='2019-04-01') & (df['short_term_deposit']==1)].head(10)

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5147585  1090829   2019-04-28  2015-10-29  ...          0             0         1
5285001  1013549   2019-04-28  2015-04-25  ...          1             0         1
5809832  1090829   2019-05-28  2015-10-29  ...          0             0         1
5834085  1013549   2019-05-28  2015-04-25  ...          1             0         1

[4 rows x 26 columns]

In [ ]:
df['loans'].value_counts()

0    5962456
1        468
Name: loans, dtype: int64

In [ ]:
df[df['loans']==1].T

                              899      ...            5946074
pk_cid                        1052170  ...            1182346
pk_partition               2018-01-28  ...         2019-05-28
entry_date                 2015-08-16  ...         2016-09-24
entry_channel                     KFC  ...                KFC
active_customer                     0  ...                  1
segment             02 - PARTICULARES  ...  02 - PARTICULARES
country_id                         ES  ...                 ES
gender                              V  ...                  H
age                                36  ...                 48
deceased                            N  ...                  N
salary                         175959  ...             149459
short_term_deposit                  0  ...                  0
loans                               1  ...                  1
mortgage                            0  ...                  0
funds                               0  ...                  0
securities                          0  ...                  0
long_term_deposit                   0  ...                  0
em_account_pp                       0  ...                  0
credit_card                         1  ...                  1
payroll                             0  ...                  0
pension_plan                        0  ...                  0
payroll_account                     0  ...                  0
emc_account                         0  ...                  0
debit_card                          0  ...                  1
em_account_p                        0  ...                  0
em_acount                           0  ...                  1

[26 rows x 468 columns]

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['loans']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5155428  1118385   2019-04-28  2016-01-17  ...          0             0         1
5180015  1077895   2019-04-28  2015-10-09  ...          1             0         1
5180238  1078181   2019-04-28  2015-10-09  ...          1             0         0
5189381  1075423   2019-04-28  2018-04-14  ...          0             0         0
5191898  1075139   2019-04-28  2015-10-04  ...          1             0         0
5224056  1137267   2019-04-28  2016-06-13  ...          0             0         1
5224814  1138345   2019-04-28  2016-06-25  ...          1             0         0
5230123  1126797   2019-04-28  2016-10-04  ...          0             0         0
5233020  1134495   2019-04-28  2016-05-20  ...          1             0         0
5254872  1031343   2019-04-28  2015-07-25  ...          1             0         1
5293529  1398523   2019-04-28  2019-03-23  ...          0             0         0
5295513  1395591   2019-04-28  2018-05-06  ...          1             0         0
5295736  1381221   2019-04-28  2018-02-09  ...          1             0         1
5331740  1371167   2019-04-28  2017-12-22  ...          1             0         0
5426456  1254567   2019-04-28  2017-04-22  ...          1             0         1
5444421  1203441   2019-04-28  2016-10-21  ...          1             0         1
5498387  1276205   2019-04-28  2017-07-24  ...          1             0         1
5554076  1398523   2019-05-28  2019-03-23  ...          0             0         0
5559575  1395591   2019-05-28  2018-05-06  ...          1             0         0
5573691  1371167   2019-05-28  2017-12-22  ...          1             0         0
5580206  1381221   2019-05-28  2018-02-09  ...          1             0         1
5609866  1276205   2019-05-28  2017-07-24  ...          1             0         1
5765186  1075139   2019-05-28  2015-10-04  ...          1             0         0
5765556  1075423   2019-05-28  2018-04-14  ...          0             0         0
5767276  1077895   2019-05-28  2015-10-09  ...          1             0         1
5806193  1078181   2019-05-28  2015-10-09  ...          1             0         0
5818285  1031343   2019-05-28  2015-07-25  ...          1             0         1
5869752  1203441   2019-05-28  2016-10-21  ...          1             0         1
5888214  1254567   2019-05-28  2017-04-22  ...          1             0         1
5909518  1138345   2019-05-28  2016-06-25  ...          1             0         0
5921001  1118385   2019-05-28  2016-01-17  ...          0             0         1
5926714  1134495   2019-05-28  2016-05-20  ...          1             0         0
5928379  1137267   2019-05-28  2016-06-13  ...          0             0         1
5933135  1126797   2019-05-28  2016-10-04  ...          0             0         0

[34 rows x 26 columns]

In [ ]:
df['mortgage'].value_counts()

0    5962600
1        324
Name: mortgage, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-28') & (df['mortgage']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5134567   330599   2019-04-28  2016-11-21  ...          1             0         0
5152683  1120077   2019-04-28  2016-01-31  ...          1             0         1
5173422  1051389   2019-04-28  2015-08-13  ...          1             0         0
5222223  1140077   2019-04-28  2016-07-08  ...          1             0         0
5233551  1136531   2019-04-28  2016-06-06  ...          1             0         0
5246294  1148111   2019-04-28  2016-07-25  ...          1             0         0
5250730   940553   2019-04-28  2016-03-26  ...          0             0         0
5431448  1258071   2019-04-28  2017-09-17  ...          0             0         0
5441855  1200307   2019-04-28  2016-10-15  ...          1             0         0
5521587   940553   2019-05-28  2016-03-26  ...          0             0         0
5524682   330599   2019-05-28  2016-11-21  ...          1             0         0
5774726  1051389   2019-05-28  2015-08-13  ...          1             0         0
5872540  1200307   2019-05-28  2016-10-15  ...          1             0         0
5889860  1258071   2019-05-28  2017-09-17  ...          0             0         0
5908497  1140077   2019-05-28  2016-07-08  ...          1             0         0
5916999  1148111   2019-05-28  2016-07-25  ...          1             0         0
5920097  1120077   2019-05-28  2016-01-31  ...          1             0         1
5929743  1136531   2019-05-28  2016-06-06  ...          1             0         0

[18 rows x 26 columns]

In [ ]:
df['funds'].value_counts()

0    5942825
1      20099
Name: funds, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-28') & (df['funds']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080338   654801   2019-04-28  2017-02-13  ...          0             0         1
5080439   660951   2019-04-28  2016-12-30  ...          0             0         1
5080546   639019   2019-04-28  2017-11-24  ...          0             0         1
5080625   720905   2019-04-28  2015-12-17  ...          0             0         1
5080631   718059   2019-04-28  2018-02-13  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5956809  1168701   2019-05-28  2016-08-23  ...          1             0         1
5957562  1172935   2019-05-28  2016-09-05  ...          0             0         0
5957646  1173075   2019-05-28  2016-09-05  ...          0             0         0
5960551  1164145   2019-05-28  2016-08-12  ...          0             0         1
5961778  1168491   2019-05-28  2016-08-22  ...          1             0         1

[1365 rows x 26 columns]

In [ ]:
df['securities'].value_counts()

0    5940791
1      22133
Name: securities, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-28') & (df['securities']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080389   650085   2019-04-28  2016-07-04  ...          0             0         1
5080543   639253   2019-04-28  2017-12-01  ...          1             0         1
5080622   721347   2019-04-28  2018-08-06  ...          1             0         1
5080660   712455   2019-04-28  2015-04-19  ...          1             0         0
5080688   735727   2019-04-28  2019-03-02  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5961191  1167673   2019-05-28  2016-08-20  ...          0             0         1
5961246  1167875   2019-05-28  2016-08-20  ...          0             0         1
5961330  1167837   2019-05-28  2016-08-20  ...          0             0         1
5961514  1167411   2019-05-28  2016-08-19  ...          0             0         1
5962399  1166325   2019-05-28  2016-08-14  ...          0             0         1

[1790 rows x 26 columns]

In [ ]:
df['long_term_deposit'].value_counts()

0    5862264
1     100660
Name: long_term_deposit, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-28') & (df['long_term_deposit']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080314   897403   2019-04-28  2015-11-22  ...          0             0         1
5080319   897613   2019-04-28  2018-07-22  ...          0             0         0
5080338   654801   2019-04-28  2017-02-13  ...          0             0         1
5080344   657905   2019-04-28  2017-02-07  ...          0             0         1
5080393   669969   2019-04-28  2017-10-17  ...          0             0         0
...          ...          ...         ...  ...        ...           ...       ...
5961544  1167453   2019-05-28  2016-08-19  ...          0             0         1
5961626  1168259   2019-05-28  2016-08-21  ...          0             0         1
5961664  1168287   2019-05-28  2016-08-21  ...          0             0         1
5961729  1168517   2019-05-28  2016-08-22  ...          0             0         1
5962394  1166331   2019-05-28  2016-12-10  ...          1             0         0

[6194 rows x 26 columns]

In [ ]:
df['em_account_pp'].value_counts()

0    5962924
Name: em_account_pp, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-28') & (df['em_account_pp']==1)]

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
df['credit_card'].value_counts()

0    5892058
1      70866
Name: credit_card, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['credit_card']==1)].head(10)

         pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080307  896359   2019-04-28  2016-09-27  ...          0             0         0
5080313  897485   2019-04-28  2016-02-25  ...          1             0         0
5080368  644941   2019-04-28  2016-04-23  ...          0             0         0
5080369  644925   2019-04-28  2016-05-21  ...          0             0         0
5080381  651789   2019-04-28  2016-01-18  ...          1             0         1
5080481  622277   2019-04-28  2015-01-01  ...          0             0         0
5080537  617099   2019-04-28  2015-02-02  ...          0             0         0
5080554  637491   2019-04-28  2017-03-13  ...          0             0         1
5080660  712455   2019-04-28  2015-04-19  ...          1             0         0
5080692  734299   2019-04-28  2015-06-21  ...          1             0         0

[10 rows x 26 columns]

In [ ]:
df['payroll'].value_counts()

0.0    5757137
1.0     205787
Name: payroll, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['payroll']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080311   897501   2019-04-28  2018-04-28  ...          1             0         0
5080333   895495   2019-04-28  2017-03-12  ...          0             0         0
5080352   656415   2019-04-28  2015-02-24  ...          1             0         0
5080368   644941   2019-04-28  2016-04-23  ...          0             0         0
5080447   665381   2019-04-28  2016-08-23  ...          1             0         0
...          ...          ...         ...  ...        ...           ...       ...
5962673  1167109   2019-05-28  2016-08-16  ...          1             0         0
5962683  1167093   2019-05-28  2016-08-16  ...          1             0         1
5962686  1167089   2019-05-28  2016-08-16  ...          1             0         0
5962719  1166671   2019-05-28  2016-08-14  ...          1             0         0
5962872  1166753   2019-05-28  2016-08-14  ...          1             0         0

[15830 rows x 26 columns]

In [ ]:
df['pension_plan'].value_counts()

0.0    5745122
1.0     217802
Name: pension_plan, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['pension_plan']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080311   897501   2019-04-28  2018-04-28  ...          1             0         0
5080313   897485   2019-04-28  2016-02-25  ...          1             0         0
5080333   895495   2019-04-28  2017-03-12  ...          0             0         0
5080341   652139   2019-04-28  2015-12-24  ...          1             0         0
5080352   656415   2019-04-28  2015-02-24  ...          1             0         0
...          ...          ...         ...  ...        ...           ...       ...
5962673  1167109   2019-05-28  2016-08-16  ...          1             0         0
5962683  1167093   2019-05-28  2016-08-16  ...          1             0         1
5962686  1167089   2019-05-28  2016-08-16  ...          1             0         0
5962719  1166671   2019-05-28  2016-08-14  ...          1             0         0
5962872  1166753   2019-05-28  2016-08-14  ...          1             0         0

[16869 rows x 26 columns]

In [ ]:
df['payroll_account'].value_counts()

0    5633504
1     329420
Name: payroll_account, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['payroll_account']==1)].head(10)

         pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080303  896451   2019-04-28  2016-01-31  ...          1             0         0
5080311  897501   2019-04-28  2018-04-28  ...          1             0         0
5080313  897485   2019-04-28  2016-02-25  ...          1             0         0
5080341  652139   2019-04-28  2015-12-24  ...          1             0         0
5080352  656415   2019-04-28  2015-02-24  ...          1             0         0
5080368  644941   2019-04-28  2016-04-23  ...          0             0         0
5080400  667063   2019-04-28  2015-08-08  ...          1             0         1
5080419  674237   2019-04-28  2018-06-14  ...          1             0         0
5080427  672927   2019-04-28  2016-03-06  ...          1             0         0
5080447  665381   2019-04-28  2016-08-23  ...          1             0         0

[10 rows x 26 columns]

In [ ]:
df['emc_account'].value_counts()

0    5635963
1     326961
Name: emc_account, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['emc_account']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080303   896451   2019-04-28  2016-01-31  ...          1             0         0
5080313   897485   2019-04-28  2016-02-25  ...          1             0         0
5080315   897431   2019-04-28  2015-07-24  ...          1             0         1
5080322   895031   2019-04-28  2015-03-07  ...          0             0         1
5080350   656163   2019-04-28  2018-06-18  ...          0             0         1
...          ...          ...         ...  ...        ...           ...       ...
5962656  1167043   2019-05-28  2016-08-16  ...          0             0         1
5962662  1167037   2019-05-28  2016-08-16  ...          1             0         1
5962683  1167093   2019-05-28  2016-08-16  ...          1             0         1
5962688  1167085   2019-05-28  2016-08-16  ...          0             0         0
5962691  1167081   2019-05-28  2016-08-16  ...          0             0         0

[23837 rows x 26 columns]

In [ ]:
df['debit_card'].value_counts()

0    5399956
1     562968
Name: debit_card, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['debit_card']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080303   896451   2019-04-28  2016-01-31  ...          1             0         0
5080305   896493   2019-04-28  2019-02-29  ...          1             0         1
5080311   897501   2019-04-28  2018-04-28  ...          1             0         0
5080312   897495   2019-04-28  2017-10-06  ...          1             0         1
5080313   897485   2019-04-28  2016-02-25  ...          1             0         0
...          ...          ...         ...  ...        ...           ...       ...
5962679  1167099   2019-05-28  2016-08-16  ...          1             0         1
5962683  1167093   2019-05-28  2016-08-16  ...          1             0         1
5962686  1167089   2019-05-28  2016-08-16  ...          1             0         0
5962719  1166671   2019-05-28  2016-08-14  ...          1             0         0
5962872  1166753   2019-05-28  2016-08-14  ...          1             0         0

[42749 rows x 26 columns]

In [ ]:
df['em_account_p'].value_counts()

0    5962890
1         34
Name: em_account_p, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['em_account_p']==1)].head(10)

Empty DataFrame
Columns: [pk_cid, pk_partition, entry_date, entry_channel, active_customer, segment, country_id, gender, age, deceased, salary, short_term_deposit, loans, mortgage, funds, securities, long_term_deposit, em_account_pp, credit_card, payroll, pension_plan, payroll_account, emc_account, debit_card, em_account_p, em_acount]
Index: []

In [ ]:
df['em_acount'].value_counts()

1    4381602
0    1581322
Name: em_acount, dtype: int64

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['em_acount']==1)]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080302   897037   2019-04-28  2016-09-04  ...          0             0         1
5080305   896493   2019-04-28  2019-02-29  ...          1             0         1
5080312   897495   2019-04-28  2017-10-06  ...          1             0         1
5080314   897403   2019-04-28  2015-11-22  ...          0             0         1
5080315   897431   2019-04-28  2015-07-24  ...          1             0         1
...          ...          ...         ...  ...        ...           ...       ...
5962915  1166769   2019-05-28  2016-08-14  ...          0             0         1
5962917  1166767   2019-05-28  2016-08-14  ...          0             0         1
5962919  1166765   2019-05-28  2016-08-14  ...          0             0         1
5962921  1166763   2019-05-28  2016-08-14  ...          0             0         1
5962922  1166789   2019-05-28  2016-08-14  ...          0             0         1

[296220 rows x 26 columns]

In [ ]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5962924 entries, 0 to 5962923
Columns: 26 entries, pk_cid to em_acount
dtypes: float64(4), int64(15), object(7)
memory usage: 1.2+ GB

In [ ]:
df[(df['pk_cid']) & (df['deceased']=='S')]

          pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
4761     1054415   2018-01-28  2015-08-28  ...          0             0         1
4812     1054155   2018-01-28  2015-08-27  ...          1             0         1
18967    1061593   2018-01-28  2015-09-17  ...          1             0         1
22325    1028045   2018-01-28  2015-07-23  ...          0             0         1
40009    1106173   2018-01-28  2015-11-27  ...          1             0         1
...          ...          ...         ...  ...        ...           ...       ...
5927303  1134587   2019-05-28  2016-05-20  ...          0             0         1
5930368  1125539   2019-05-28  2016-03-25  ...          0             0         0
5932644  1131765   2019-05-28  2016-04-26  ...          0             0         0
5935746  1181419   2019-05-28  2016-09-23  ...          0             0         1
5947659  1184647   2019-05-28  2016-09-27  ...          0             0         1

[590 rows x 26 columns]

In [ ]:
df[(df['pk_cid']) & (df['pk_partition']>='2019-04-01') & (df['credit_card']==1)].head(10)

         pk_cid pk_partition  entry_date  ... debit_card  em_account_p em_acount
5080307  896359   2019-04-28  2016-09-27  ...          0             0         0
5080313  897485   2019-04-28  2016-02-25  ...          1             0         0
5080368  644941   2019-04-28  2016-04-23  ...          0             0         0
5080369  644925   2019-04-28  2016-05-21  ...          0             0         0
5080381  651789   2019-04-28  2016-01-18  ...          1             0         1
5080481  622277   2019-04-28  2015-01-01  ...          0             0         0
5080537  617099   2019-04-28  2015-02-02  ...          0             0         0
5080554  637491   2019-04-28  2017-03-13  ...          0             0         1
5080660  712455   2019-04-28  2015-04-19  ...          1             0         0
5080692  734299   2019-04-28  2015-06-21  ...          1             0         0

[10 rows x 26 columns]

In [ ]:
df.head().T

                                    0  ...                   4
pk_cid                        1375586  ...             1050614
pk_partition               2018-01-28  ...          2018-01-28
entry_date                 2018-01-12  ...          2015-08-10
entry_channel                     KHL  ...                 KHE
active_customer                     1  ...                   1
segment             02 - PARTICULARES  ...  03 - UNIVERSITARIO
country_id                         ES  ...                  ES
gender                              H  ...                   V
age                                35  ...                  23
deceased                            N  ...                   N
salary                        87218.1  ...              114978
short_term_deposit                  0  ...                   0
loans                               0  ...                   0
mortgage                            0  ...                   0
funds                               0  ...                   0
securities                          0  ...                   0
long_term_deposit                   0  ...                   0
em_account_pp                       0  ...                   0
credit_card                         0  ...                   0
payroll                             0  ...                   0
pension_plan                        0  ...                   0
payroll_account                     0  ...                   0
emc_account                         0  ...                   0
debit_card                          0  ...                   0
em_account_p                        0  ...                   0
em_acount                           1  ...                   1

[26 rows x 5 columns]

Creo un DF nuevo para analizar las ventas del ultimo mes y poder realizar cuantos productos hemos vendido este mes o si son los clientes nuevos qui√©nes
contratan o los que ya ten√≠amos!

In [ ]:
df1= df[['pk_cid','entry_date','pk_partition', 'segment','short_term_deposit','loans','mortgage','funds','securities','long_term_deposit','em_account_pp','credit_card','payroll','pension_plan','payroll_account','emc_account',
          'debit_card', 'em_account_p','em_acount' ]]
df1

          pk_cid  entry_date pk_partition  ... debit_card  em_account_p  em_acount
0        1375586  2018-01-12   2018-01-28  ...          0             0          1
1        1050611  2015-08-10   2018-01-28  ...          0             0          1
2        1050612  2015-08-10   2018-01-28  ...          0             0          1
3        1050613  2015-08-10   2018-01-28  ...          0             0          0
4        1050614  2015-08-10   2018-01-28  ...          0             0          1
...          ...         ...          ...  ...        ...           ...        ...
5962919  1166765  2016-08-14   2019-05-28  ...          0             0          1
5962920  1166764  2016-08-14   2019-05-28  ...          0             0          1
5962921  1166763  2016-08-14   2019-05-28  ...          0             0          1
5962922  1166789  2016-08-14   2019-05-28  ...          0             0          1
5962923  1550586  2019-05-13   2019-05-28  ...          0             0          1

[5962924 rows x 19 columns]

In [ ]:
df1.groupby('entry_date').sum().reset_index()

      entry_date      pk_cid  ...  em_account_p  em_acount
0     2015-01-01    10578709  ...             0          0
1     2015-01-02  2718809383  ...             0       1870
2     2015-01-03  1384019916  ...             0        899
3     2015-01-04  1151920331  ...             0        577
4     2015-01-05   763453104  ...             0        313
...          ...         ...  ...           ...        ...
1494  2019-05-27   186256966  ...             0         14
1495  2019-05-28    78986934  ...             0          6
1496  2019-05-29   108104102  ...             0          8
1497  2019-05-30   307060014  ...             0         14
1498  2019-05-31   233753307  ...             0          4

[1499 rows x 17 columns]

In [ ]:
ventas = df1.groupby('entry_date').sum().reset_index()
ventas

      entry_date      pk_cid  ...  em_account_p  em_acount
0     2015-01-01    10578709  ...             0          0
1     2015-01-02  2718809383  ...             0       1870
2     2015-01-03  1384019916  ...             0        899
3     2015-01-04  1151920331  ...             0        577
4     2015-01-05   763453104  ...             0        313
...          ...         ...  ...           ...        ...
1494  2019-05-27   186256966  ...             0         14
1495  2019-05-28    78986934  ...             0          6
1496  2019-05-29   108104102  ...             0          8
1497  2019-05-30   307060014  ...             0         14
1498  2019-05-31   233753307  ...             0          4

[1499 rows x 17 columns]

In [ ]:
ventas_ultimo_mes = ventas[(ventas['entry_date']>='2019-04-01')].sum().T
ventas_ultimo_mes

entry_date            2019-04-012019-04-022019-04-032019-04-042019-0...
pk_cid                                                      19741579619
short_term_deposit                                                    0
loans                                                                 0
mortgage                                                              0
funds                                                                 9
securities                                                            8
long_term_deposit                                                     1
em_account_pp                                                         0
credit_card                                                          26
payroll                                                             235
pension_plan                                                        242
payroll_account                                                     209
emc_account                                                          75
debit_card                                                          442
em_account_p                                                          0
em_acount                                                          5313
dtype: object

In [ ]:
ventas1 = df1.groupby('pk_partition').sum().reset_index()
ventas1

   pk_partition        pk_cid  ...  em_account_p  em_acount
0    2018-01-28  282482053209  ...             2     215293
1    2018-02-28  286630055694  ...             2     217098
2    2018-03-28  290395942848  ...             2     218683
3    2018-04-28  293473304894  ...             2     219816
4    2018-05-28  296862880725  ...             2     221291
5    2018-06-28  299912655038  ...             2     224328
6    2018-07-28  409318839308  ...             2     234324
7    2018-08-28  428802349272  ...             2     245980
8    2018-09-28  461322910658  ...             2     261210
9    2018-10-28  501283001762  ...             2     277707
10   2018-11-28  522498984113  ...             2     284900
11   2018-12-28  531752191814  ...             2     288928
12   2019-01-28  538533727170  ...             2     291786
13   2019-02-28  545992054358  ...             2     292988
14   2019-03-28  552876327689  ...             2     295046
15   2019-04-28  558216581658  ...             2     295844
16   2019-05-28  563438682489  ...             2     296380

[17 rows x 17 columns]

investigar como saber que cliente se ha ido y cuales ha dado alta en este mes

In [ ]:
ventas_ultimo_mes1 = ventas1[ventas1['pk_partition']>='2019-04-01'].T
ventas_ultimo_mes1

                              15            16
pk_partition          2019-04-28    2019-05-28
pk_cid              558216581658  563438682489
short_term_deposit             2             2
loans                         30            30
mortgage                      23            23
funds                       1320          1315
securities                  1782          1789
long_term_deposit           6368          6129
em_account_pp                  0             0
credit_card                 4747          4801
payroll                    15231         16333
pension_plan               16220         17353
payroll_account            25501         26529
emc_account                23455         24751
debit_card                 42140         43261
em_account_p                   2             2
em_acount                 295844        296380

Exporto el DataSets para graficar con Power BI

In [ ]:
ventas_ultimo_mes.to_excel('/content/drive/MyDrive/Proyecto Final/data/ventas_ultimo_mes.xlsx')

In [ ]:
ventas_ultimo_mes1.to_excel('/content/drive/MyDrive/Proyecto Final/data/ventas_ultimo_mes1.xlsx')

In [ ]:
##ventas_ultimo_mes.to_excel('C:/Mis Datos en Local/Project/data/ventas_ultimos_meses.xlsx', index=False)

In [ ]:
ventas_ultimo_mes.to_csv('/content/drive/MyDrive/Proyecto Final/data/ventas_ultimo_mes.csv')

In [ ]:
ventas_ultimo_mes1.to_csv('/content/drive/MyDrive/Proyecto Final/data/ventas_ultimo_mes1.csv')